pipeline {
    agent any
    environment {
     PATH = "/opt/maven/bin:$WORKSPACE:$PATH"
     
     // SonarQube Environment
     SONAR_HOST_URL = 'http://98.84.68.78:9000'
     SONAR_PROJECT_KEY = 'back-end-project'  // Replace with your project key
     //SONAR_LOGIN = credentials('sonar_cred')  // Credentials to authenticate with SonarQube
     SONARQUBE_AUTH_TOKEN = credentials('sonar_token')
     
     // Artifactory details
     ARTIFACTORY_URL = 'http://98.84.68.78:8082'
     ARTIFACTORY_REPO = 'maven1512'
     ARTIFACTORY_CREDENTIALS_ID = 'jfrog_cred'
    }
    stages {
        stage('Checkout Code') {
            steps {
        //     git url: 'https://github.com/jenkins-docs/simple-java-maven-app.git', branch: 'master'
        //     git url: 'https://github.com/kapilkumaria/simple-java-maven-app.git', branch: 'master'
               git url: 'https://github.com/kapilkumaria/CI-pipeline-with-jenkins-sonarqube-and-jfrog.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube Analysis') {
         steps {
             withSonarQubeEnv('sonarqube') {
                 sh 'mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN'
             }
           }
        }
        stage('Upload to Artifactory') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jfrog_cred', usernameVariable: 'ARTIFACTORY_USER', passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                 // Add the server configuration
                     sh '''
                         jfrog config add artifactory-server-kk --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
                     '''
                // Upload artifact
                     sh '''
                         jfrog rt u target/*.jar $ARTIFACTORY_REPO/$(date +%Y-%m-%d)/ --build-name=my-build --build-number=$BUILD_NUMBER
                     '''
                }
            } 
        }
   }
}

