pipeline {
    agent any
    environment {
     PATH = "/opt/maven/bin:$WORKSPACE:$PATH"
    }
    stages {
        stage('Checkout Code') {
            steps {
        //     git url: 'https://github.com/jenkins-docs/simple-java-maven-app.git', branch: 'master'
        //     git url: 'https://github.com/kapilkumaria/simple-java-maven-app.git', branch: 'master'
               git url: 'https://github.com/kapilkumaria/CI-pipeline-with-jenkins-sonarqube-and-jfrog.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
